name: auto_Reserve

on:

  workflow_dispatch:  # 保留手动触发功能

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 设置3小时超时防止意外终止
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
          pip install cryptography requests opencv-python numpy pytz

      - name: run script
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
        run: |
          # 添加时间检查确保执行时机正确
          echo "当前UTC时间: $(date -u)"
          echo "当前北京时间: $(TZ='Asia/Shanghai' date)"
          python main.py -m reserve --action
